$NetBSD: patch-Cargo.toml,v 1.1 2021/04/06 20:40:12 wiz Exp $

Provide unpublished crate manually rather than fetch with git.

--- Cargo.toml.orig	2021-01-10 13:55:04.000000000 +0000
+++ Cargo.toml
@@ -63,10 +63,10 @@ byteorder = "1.3"
 bytes = { version = "0.5", optional = true }
 chashmap = "2.2"
 cfg-if = "0.1"
-citeproc = { git = "https://github.com/cormacrelf/citeproc-rs", rev = "68c7a7c16088b5d7751641ab37299ad064cdb221", optional = true }
-citeproc-db = { git = "https://github.com/cormacrelf/citeproc-rs", rev = "68c7a7c16088b5d7751641ab37299ad064cdb221", optional = true }
-citeproc-io = { git = "https://github.com/cormacrelf/citeproc-rs", rev = "68c7a7c16088b5d7751641ab37299ad064cdb221", optional = true }
-csl = { git = "https://github.com/cormacrelf/citeproc-rs", rev = "68c7a7c16088b5d7751641ab37299ad064cdb221", optional = true }
+citeproc = { path = "../citeproc-rs/crates/citeproc", optional = true }
+citeproc-db = { path = "../citeproc-rs/crates/db", optional = true }
+citeproc-io = { path = "../citeproc-rs/crates/io", optional = true }
+csl = { path = "../citeproc-rs/crates/csl", optional = true }
 fern = "0.6"
 fnv = { version = "1.0", optional = true }
 futures = "0.3"
