$NetBSD: patch-Cargo.toml,v 1.2 2021/06/28 10:42:50 wiz Exp $

Provide unpublished crate manually rather than fetch with git.

--- Cargo.toml.orig	2021-06-12 14:13:55.000000000 +0000
+++ Cargo.toml
@@ -37,10 +37,10 @@ byteorder = "1.4.3"
 cancellation = "0.1"
 cfg-if = "1.0.0"
 chashmap = "2.2.2"
-citeproc = { git = "https://github.com/cormacrelf/citeproc-rs", rev = "68c7a7c16088b5d7751641ab37299ad064cdb221", optional = true }
-citeproc-db = { git = "https://github.com/cormacrelf/citeproc-rs", rev = "68c7a7c16088b5d7751641ab37299ad064cdb221", optional = true }
-citeproc-io = { git = "https://github.com/cormacrelf/citeproc-rs", rev = "68c7a7c16088b5d7751641ab37299ad064cdb221", optional = true }
-csl = { git = "https://github.com/cormacrelf/citeproc-rs", rev = "68c7a7c16088b5d7751641ab37299ad064cdb221", optional = true }
+citeproc = { path = "../citeproc-rs/crates/citeproc", optional = true }
+citeproc-db = { path = "../citeproc-rs/crates/db", optional = true }
+citeproc-io = { path = "../citeproc-rs/crates/io", optional = true }
+csl = { path = "../citeproc-rs/crates/csl", optional = true }
 crossbeam-channel = "0.5.1"
 cstree = "0.5.0"
 derive_more = "0.99.14"
