$NetBSD: patch-Cargo.toml,v 1.2 2021/04/03 19:03:44 tnn Exp $

Provide unpublished crate manually rather than fetch with git.

--- Cargo.toml.orig	2021-03-22 19:39:10.000000000 +0000
+++ Cargo.toml
@@ -8,8 +8,7 @@ edition = "2018"
 crate-type = ["staticlib"]
 
 [dependencies.timescale-extension-utils]
-git = "https://github.com/timescale/timescale-extension-utils"
-branch = "master"
+path = "timescale-extension-utils"
 
 [profile.release]
 lto = true
